# app/exceptions/__init__.py
